version: 2.1
jobs:
  compile:
    docker:
      - image: thagoo/Triton:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone https://github.com/Thagoo/Triton_kernel_xiaomi_msm8917 -b tr-10-caf triton
      - run: wget https://raw.githubusercontent.com/Thagoo/scripts/master/rolex/drone
      - run: chmod +x drone
      - run: bash drone

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile