kind: pipeline
type: docker
name: triton

steps:
  - name: Compile
    image: ubuntu:latest
    environment:
    token:
      from_secret: TOKEN
    cid:
      from_secret: CID
    commands:
      - apt-get install -y bison build-essential bc bison curl libssl-dev git6 zip wget
      - wget https://raw.githubusercontent.com/Thagoo/triton-script/tr/compiler.sh
      - chmod +x compiler.sh
      - bash compiler.sh
